CRUD_cms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path,include
from . import views
from core import views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


app_name = 'core'

urlpatterns = [
              path('',views.IndexView.as_view(), name='index'),
              path('post/',views.PostView.as_view(), name='post'),
              path('add/',views.AddView.as_view(), name='add'),
              path('admin_login/',views.LoginView.as_view(template_name='admin_login.html'), name='admin_login'),
              path('<slug:slug>/',views.SingleView.as_view(), name ='single'),
              path('edit/<int:pk>',views.EditView.as_view(), name='edit'),
              path('delete/<int:pk>',views.Delete.as_view(), name='delete'),
              #path('logout',views.Logout, name='logout'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Core(models.Model):
	title = models.CharField(max_length=200)
	excerpt = models.TextField(null = True)
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')
	slug = models.SlugField(max_length=100, unique = True)
	updated = models.DateTimeField(auto_now=True)
	image = models.ImageField(upload_to='profile_pics')
	published = models.DateTimeField(default = timezone.now)

	def get_absolute_url(self):
		return reverse('core:single',args =[self.slug])

	class Meta:
		ordering = ['-published']

	def __str__(self):
		return self.title

	

core/forms.py
from django import forms
from .models import Core

class PostForm(forms.ModelForm):
	class Meta:
		model = Core
		fields = ('title','excerpt','author','slug','image','published')

core/views.py
from django.shortcuts import render,redirect
from .models import Core
from django.views.generic import ListView, DetailView, UpdateView, CreateView,DeleteView, View, TemplateView
from django.urls import reverse_lazy
from .forms import PostForm
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,logout,login
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
# Create your views here.
class IndexView(ListView):
	model = Core
	template_name = 'index.html'
	context_object_name = 'index'

class SingleView(DetailView):
	model = Core
	template_name = 'single.html'
	context_object_name = 'post'

@method_decorator(staff_member_required,name='dispatch')
class PostView(ListView):
	model = Core
	template_name = 'post.html'
	context_object_name = 'post_list'

class AddView(CreateView):
	model = Core
	template_name = 'add.html'
	fields = '__all__'
	success_url = reverse_lazy('core:post')

class EditView(UpdateView):
	model = Core
	template_name = 'edit.html'
	fields = '__all__'
	pk_url_kwarg = 'pk'
	success_url = reverse_lazy('core:post')


class Delete(DeleteView):
	model = Core
	pk_url_kwarg = 'pk'
	success_url = reverse_lazy('core:post')
	template_name = 'delete.html'

class LoginView(TemplateView):

	def post(self,request):
		if request.method=='POST':
			username = request.POST['username']
			password = request.POST['password']

			user = authenticate(username = username,password=password)
			if user.is_staff:
				login(request,user)
				return HttpResponseRedirect('/post')
		else:
			template_name = 'admin_login.html'		



   

core/templates/ad_nav.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}

.topnav .icon {
  display: none;
}

@media screen and (max-width: 600px) {
  .topnav a:not(:first-child) {display: none;}
  .topnav a.icon {
    float: right;
    display: block;
  }
}

@media screen and (max-width: 600px) {
  .topnav.responsive {position: relative;}
  .topnav.responsive .icon {
    position: absolute;
    right: 0;
    top: 0;
  }
  .topnav.responsive a {
    float: none;
    display: block;
    text-align: left;
  }
}

/* Style the header */

</style>
</head>
<body>


<div class="topnav" id="myTopnav">
  
  <a href="{% url 'core:admin_login' %}">Manage post</a>
  <a href="{%url 'logout'%}">Logout</a>
  

  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>



<script>
function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}
</script>

</body>
</html>

core/templates/add.html
{% extends 'base.html' %}

{% block content %}
{%load widget_tweaks%}
{% load static %}

<div class="container pt-5">
	<form method="post" novalidate enctype="multipart/form-data" action="">
		{% csrf_token%}
		{% for field in form.visible_fields%}
		<div class="form-group">
			<label for = "{{field.id_for_label}}">{{field.label}}</label>
			{{field|add_class:'form-control'}}
		
			{% for error in field.errors%}
			<span class="help-block">{{error}}</span>
			{% endfor %}
		</div>
		{% endfor%}
	
		<div class="form-group">
			<button type='submit' class="btn btn-success">
				<span class="glyphicon glyphicon-ok"></span>Add
			</button>
			<a href="{% url 'core:post'%}" class="btn btn-default">cancel</a>
			
		</div>
	</form>
</div>
{% endblock %}

core/templates/admin_login.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <title>Login Page</title>

  <style>
        body{
            margin: 0;
            padding: 0;
        }
        body:before{
            content: '';
            position: fixed;
            width: 100vw;
            height: 100vh;
            background-image: url("{% static "images/lake.jpg" %}");
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
            -webkit-filter: blur(10px);
            -moz-filter: blur(10px);
            -o-filter: blur(10px);
            -ms-filter: blur(10px);
            filter: blur(5px);
        }
        .login-form
        {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%,-50%);
            width: 400px;
            height: 450px;
            padding: 80px 40px;
            box-sizing: border-box;
            background: rgba(0,0,0,.5);
        }
        .avatar {
            position: absolute;
            width: 80px;
            height: 80px;
            border-radius: 50%;
            overflow: hidden;
            top: calc(-80px/2);
            left: calc(50% - 40px);
        }
        .login-form h2 {
            margin: 0;
            padding: 0 0 20px;
            color: #fff;
            text-align: center;
            text-transform: uppercase;
        }
        .login-form p
        {
            margin: 0;
            padding: 0;
            font-weight: bold;
            color: #fff;
        }
        .login-form input
        {
            width: 100%;
            margin-bottom: 20px;
        }
        .login-form input[type="text"],
        .login-form input[type="password"]
        {
            border: none;
            border-bottom: 1px solid #fff;
            background: transparent;
            outline: none;
            height: 40px;
            color: #fff;
            font-size: 16px;
        }
        .login-form input[type="submit"] {
            height: 30px;
            color: #fff;
            font-size: 15px;
            background: red;
            cursor: pointer;
            border-radius: 25px;
            border: none;
            outline: none;
            margin-top: 10%;
        }
        .login-form a
        {
            color: #fff;
            font-size: 14px;
            font-weight: bold;
            text-decoration: none;
        }
        input[type="checkbox"] {
            width: 20%;
        }
    </style>

</head>
<body>

  <!-- <form method="post">
    {% csrf_token %}
    <input type="username" name="username" placeholder="UserName" required><br>
    <input type="password" name="password" placeholder="Password" required><br>
    <input type="submit">
  </form> -->

  <div class="login-form">
      <img src="{% static 'images/computer.png' %}" class="avatar">
      <h2>Admin Login</h2>
      <form method="post">
    {% csrf_token %}
      <p>User Name</p>
      <input type="text" name="username" placeholder="Enter User Name" required>
      <p>Password</p>
      <input type="password" name="password" placeholder="Enter Password" required>
      <input type="submit" name="submit" value="Sign In"><br><br>
      <a href="#" style="color: skyblue">Don't have an account? Register HERE</a>
      <!-- <p><input type="checkbox"> Remember Me</p> -->
      </form>
        {% for message in messages %}
        {{message}}
        {% endfor %}
  </div>

</body>
</html>

core/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    
</head>
<body>
{% include 'navigation.html'%}
  {% block content %}

  {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/base1.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    
</head>
<body>
{% include 'ad_nav.html'%}
  {% block content %}

  {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/delete.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container pt-5">
	<form method="POST">
		{% csrf_token %}
		<p>Are you sure you wants to delete "{{object}}" ?</p>
		<input type="submit" value="Confirm">
		
	</form>
</div>
{% endblock %}

core/templates/edit.html
{% extends 'base.html' %}

{% block content %}
{%load widget_tweaks%}
{% load static %}

<div class="container pt-5">
	<form method="post" novalidate enctype="multipart/form-data" action="">
		{% csrf_token%}
		{% for field in form.visible_fields%}
		<div class="form-group">
			<label for = "{{field.id_for_label}}">{{field.label}}</label>
			{{field|add_class:'form-control'}}
			{% for error in field.errors%}
			<span class=""help-block>{{error}}</span>
			{% endfor %}
		</div>
		{% endfor%}
	
		<div class="form-group">
			<button type='submit' class="btn btn-success">
				<span class="glyphicon glyphicon-ok"></span>Edit
			</button>
			<a href="{% url 'core:post'%}" class="btn btn-default">cancel</a>
			
		</div>
	</form>
</div>
{% endblock %}

core/templates/index.html
{% extends 'base.html'%}

{% block content %}
{% load static %}
<head>
	    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
   


<style>

		p{
	color: #777;
	font-size: 14px;
	font-weight: 300
	line-height: 22px;
	padding: 10px;
}
		.text_book{
			width: 90%;
			color: #ffffff;
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%,-50%);
			text-align: center;
		}
		.text_book h1{

			font-size: 40px;
		}
		.text_book p{

			margin: 10px 0 40px;
			font-size: 18px;
			color: #ffffff;
		}
		

/*----------------------map--------------------*/
   	.map-responsive{
    overflow:hidden;
    padding-bottom:56.25%;
    position:relative;
    height:0;
}
.map-responsive iframe{
    left:0;
    top:0;
    height:100%;
    width:90%;
    position:absolute;
}




.banner-area {
  background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)),url("{% static 'images/bennar.jpg' %}");
  background-position: center center;
  background-size: cover;
  text-align: center;
  color: #ffffff;
  padding: 130px;
  margin-top: -20px;
  
  /*------------------footer-----------------------------*/


} 
.row{
	display: flex;
	flex-wrap: wrap;
}

.footer-col{
	width: 30%;
	padding: 0 25px;
}
.footer-col h4{
	font-size: 18px;
	color: #ffffff;
	margin-bottom: 20px;
	font-weight: 500;
	position: relative;
}
.footer-col h4::before{
	content: "";
	position: absolute;
	left: 0;
	bottom: -10px;
	background-color: #e91e63;
	height: 2px;
	box-sizing: border-box;
	}

.footer-col ul li:not(:last-child){

	margin-bottom: 10px;
}

.footer-col ul li a{
	font-size: 16px;
	color: #ffffff;
	text-decoration: none;
	font-weight: 300;
	color: #bbbbbb;
	display: block;
}

/*===responsive=====*/
@media(max-width: 767px){
	.footer-col{
		margin-left: 30px;
		width: 50%;
		margin-bottom: 30px;
	}
}
@media(max-width: 574px){
	.footer-col{
		width: 100%;
	
	}
}

 @media(max-width: 574px){
 .container{

  width: 80%;
  margin-left: 40px;
  

}
	


	</style>


</head>
<body>

<div class = 'banner-area'>
	
</div>
<div class = "text_book">
    <h1>MOST THOUGHTFUL BLOGS</h1>
 
<p>Read with a cup of coffee, or leave us a message</p>
</div><br>
<br>
<h2 style=" text-align: center; color: #000000;">OUR BLOGS</h2>


<div class = 'album py-5 bg-light'>
	<div class = 'container'>
		<div class = 'row'>
		
			{% for core in index %}

			  <div class = 'col-sm-4'>
			  	<div class = 'card m-2 '>
			  		<img class='card-img-top' src="{{core.image.url}}" alt='image'height="200px">
			  		<div class ='card_body'>
			  			<h4 class="" style="text-align: center;"><a href="{{core.get_absolute_url}}">{{core.title}}</a></h4>
			  			<p class = 'card_text'></p>	
			  			<div class ="d-flex justify-content-between align-items-center">
			  				<div class = "">
			  					<small class="text-muted">{{core.published}}</small>
			  					
			  				</div>
			  				
			  			</div>
			  		</div>
			  	</div>
			  </div>
			{% endfor %}
			
		</div>
	</div>
</div>

<footer class="footer" style="background-color: #24262b; padding: 70px 0;">
	<div class="container1" style="max-width: 1170px; margin: auto;">
		<div class="row">
			<div class="footer-col">
				<h4><u>QUICK CONTACT</u></h4>
					<ul>
						<li><a href="#"><i class="fa fa-phone"></i>&nbsp;&nbsp;+91 7827 525 27</a> </li>
						<li><a href="#"><i class="fa fa-phone"></i>&nbsp;&nbsp;+91 0120-416077</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i>&nbsp;&nbsp;info@XYZ.com</a> </li>
						<li><a href="#"><i class="fa fa-envelope-o"></i>&nbsp;&nbsp;XYZtechnology@gmail.com</a></li>
						<li><a href="#"><i class="fa fa-building"></i>&nbsp;&nbsp; Sector-63 Noida, <br>&nbsp;&nbsp;&nbsp;&nbsp;Uttar Pradesh Noida 201309, <br>&nbsp;&nbsp;&nbsp;&nbsp;INDIA</a></li>
					</ul>
				
			</div>
			
			<div class="footer-col">
				<h4><u>INTERNSHIP</u></h4>
					<ul>
						<li><a href="#">Digital Marketing</a></li>
						<li><a href="#">Php Development Internship</a></li>
						<li><a href="#">Application Development</a></li>
						<li><a href="#">Web Designing Internship</a></li>
						<li><a href="#">Asp .Net Framework</a></li>
						<li><a href="#">Java Development Internship</a></li>

					</ul>
				
			</div>

			

			<div class="footer-col">
				<h4>FOLLOW US ON GOOGLE MAP</h4>
					<ul>
						<div class="map-responsive">
     					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3503.5378611448245!2d77.31302231424728!3d28.583636982437113!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce545e8e3d255%3A0x56e07cf92b8dca7b!2sVMCODER%20TECHNOLOGY!5e0!3m2!1sen!2sin!4v1616387720051!5m2!1sen!2sin" width="350" height="350" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
   				</div>
					</ul>
				
			</div>
		</div>
		
	</div>

</footer>

</body>

{% endblock %}

core/templates/navigation.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<style>
*{
  margin:0;
  padding: 0;
  text-decoration: none;
  list-style: none;
  box-shadow: border-box;
  

}

.header{
  background-color:#f5b942;
  height:50px;
  width: 100%;
  
  top: 0;
}
.social-icons{
  float: right;
  margin-right: 5%;
}
.top-icons{
  padding: 14px 15px;
}
.top-icons a{
  padding:13px;
  color: white;
}
.top-icons a:hover{
  color: #000000;
}


/*--
nav{
  padding: px;
  background: #ffffff;
  height: 60px;
  width:100%;
  
}*/

nav ul{
  float: right;
  margin-right: 250px;
}
nav ul li{
  display: inline-block;
  line-height: 80px;
  margin:0 5px;
}
nav ul li a{
  color: #000000;
  font-size: 14px;
  font-weight: bold;
  padding: 7px 13px;
  border-radius: 3px;
  text-transform: uppercase;
}
a.active,a:hover{
  color: orange;
  transition:0.5s;
}

/* Style the header */

</style>
</head>
<body>
  

 <div class="header">
 <div class="social-icons">
   <div class="top-icons">
     <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-instagram"></i></a>
               <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-linkedin"></i></a>
                    

   </div>
 </div>

</div>

  <nav class="navbar navbar-default" >

  
   <ul class = "topnav">
     <li><a href="{% url 'core:index'%}">Home</a></li>
     <li><a href="#">About</a></li>
     <li><a href="#">Contact</a></li>
     <li><a href="{% url 'core:admin_login' %}">Manage post</a></li>

   </ul>
 </nav>

</body>
</html>

core/templates/post.html
{% extends 'base.html' %}

{% block content %}
{% load static %}



<!-------------POST------------------------>
<nav class = "navbar navbar-expand-lg navbar-light bg-light">
	<div class = 'navbar-brand'>post adminstration</div>
	<div class="collapse navbar-collapse" id = 'navbarNav'>
		<ul class = 'navbar-nav'>
			<li class = 'nav-item active'>
				<a class = 'nav-link'  href="{% url 'core:add' %}">Add new</a>
			</li>
		</ul>	
	</div>
</nav>

<div class="alubm py-5 bg-light">
	<div class="container">
		<div class='row'>
			{% for post in post_list%}
			<div class = 'col-sm-4'>
			  	<div class = 'card m-2 '>
			  		<img class='card-img-top' src="{{post.image.url}}" alt='image'height="200px">
			  		<div class ='card_body'>
			  		<h4 class="lead"><a class="text-dark" href="#">{{post.title}}</a></h4>
			  		<p class="card-text"></p>
			  		<div class ="d-flex justify-content-between align-items-center">
			  			<div class = "">
			  					<small class="text-muted">9 mins</small>
			  			<div class="btn-group">
			  				<a href="{{post.get_absolute_url}}" class="btn btn-sm btn-outline-secondary" role='button' aria-pressed='true'>View</a>
			  				<a href="{% url 'core:edit' post.pk %}" class="btn btn-sm btn-outline-secondary" role='button' aria-pressed='true'>Edit</a>
			  				<a href="{% url 'core:delete' post.pk %}" class="btn btn-sm btn-outline-secondary" role='button' aria-pressed='true'>Delete</a>
			  			</div>
			  		</div>	
				</div>
			</div>
		</div>
	</div>

			{% endfor %}
		</div>
	</div>
	
</div>


{% endblock %}

core/templates/single.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="area" style="padding-top: 0;padding-right: 15%;padding-left: 15%;">
<div class = "container">
	<div class = "row">
		<div class = "col-12 pt-5">
			<img class='card-img-top' src="{{post.image.url}}" alt='image' style="width: 100%;height: 400px;">
			<u><h2 style="text-align: center;" class = "pt-5">{{post.title}}</h2><br></u>
			<p>{{post.excerpt|linebreaks}}</p>			
		</div>
	</div>
</div>
</div>

{% endblock %}